# You can define multiple datasets, which will be analysed separately. Each
# must have data_uri, year_col, and month_col defined.
# year_col and month_col are the columns in the downloaded data in which the
# year and month for each row can be found.

datasets:
  market:
    data_uri: http://www.guardian.co.uk/business
    info_uri: 

